#!/bin/sh

git reset HEAD --hard
git clean -f
git add .

if [[ "$1" != "off" ]]; then
  git checkout local-master
else
  git checkout master
fi

git pull --force
git submodule update --init

source ~/.bashrc
