#!/bin/bash

if [[ "$1" == "dump-merge" ]]; then
  cp -r ~/.dotfiles/local_bin/* local_bin/
elif [[ "$1" == "dump" ]]; then
  rm -fr local_bin/*
  cp -r ~/.dotfiles/local_bin/* local_bin/
elif [[ "$1" == "deploy" ]]; then
  rm -fr ~/.dotfiles/local_bin/*
  cp -r local_bin/* ~/.dotfiles/local_bin/
fi
