#!/bin/sh

function red_output() {
  echo -e " \033[1;31m"
}

function ssh_exec() {
  local server=$1
  local cmd=$2

  ssh $server -t "bash --login -c '$cmd'"
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then help; fi
