#!/bin/bash

source ~/.bashrc
rvm use $(rvm current)

if [[ "$1" == "s" ]]; then
  bundle exec cap staging deploy
elif [[ "$1" == "p" ]]; then
  echo -e '\033[1;31m'
  bundle exec cap staging deploy
  echo -e '\033[0m'
elif [[ "$1" == "pm" ]]; then
  echo '\033[1;31m'
  bundle exec cap staging deploy
  echo '\033[0m'
fi
