
# # Git
# alias g="git"
# alias gs="git status"
# alias gp="git push"
# alias gpl="git pull"
# alias gc="g c"
# alias ga="g aa"
# alias be="bundle exec"
# alias bec="bundle exec cucumber"
# alias gco="git co"
# alias gl="git log --oneline --decorate"
# alias gd="git diff"
# alias gdd="git df"
# alias gitconfig="mate -w .git/config"
# # Setup a tracking branch from [remote] [branch]
# function gbt() {
#   git branch --track $2 $1/$2
#   git checkout $2
# }

# function gg() {
#   git commit -a -v -m "$*"
# }

# export DISPLAY=:0
# export JAVA_HOME='/usr/lib/jvm/jdk1.6.0_26'

# # RVM
# [[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm  # This loads RVM into a shell session.

# # Tmuxinator
# [[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

# PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
# export SSL_CERT_FILE=~/.dotfiles/cacert.pem

# export EDITOR=vim

